// {
//   "majorArcana": [
//     { "id":"1",
//       "name": "The Fool",
//       "description": "New beginnings, spontaneity, innocence.",
//       "image": "https://i.ibb.co/8B9HqgS/fool.jpg",
//       "detail" : "The Fool is a fascinating card in the Tarot deck. Represented by the number 0 or sometimes XXII, it often depicts a young person standing on the edge of a cliff, seemingly about to step off into the unknown. This card symbolizes new beginnings, spontaneity, and taking a leap of faith.The Fool is usually portrayed as carefree and optimistic, carrying a small sack that contains life's essentials. The sack is tied to a staff, suggesting that the Fool is ready for a journey. The imagery often includes a small dog at their heels, symbolizing loyalty and instinct. The Fool is sometimes portrayed looking upwards, indicating a connection to higher realms and divine guidance.    In readings, the Fool is associated with a sense of adventure and the willingness to embrace the unexpected. It suggests that the querent is on the verge of a new phase in life, and while they may not have all the answers, they are open to the possibilities. The card encourages a spirit of curiosity, trust, and a willingness to take risks.   Reversed, the Fool can indicate recklessness or naivety. It may suggest a need for caution and a reminder to consider the potential consequences of actions. However, even in the reversed position, the Fool can still carry an element of spontaneity and the opportunity for positive change if approached with awareness. Overall, the Fool embodies the essence of starting a journey, stepping into the unknown with a sense of wonder and excitement. It encourages embracing the present moment and trusting the process of life."
//     },
//     { "id":"2",
//       "name": "The Magician",
//       "description": "Manifestation, power, resourcefulness.",
//       "image": "https://i.ibb.co/C1NMrrj/magician.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"3",
//       "name": "The High Priestess",
//       "description": "Intuition, mystery, the subconscious.",
//       "image": "https://i.ibb.co/6ws81kZ/highpresstnessmajor.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"4",
//       "name": "The Empress",
//       "description": "Nurturing, abundance, fertility.",
//       "image": "https://i.ibb.co/3dz6SH9/empressarcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"5",
//       "name": "The Emperor",
//       "description": "Authority, leadership, structure.",
//       "image": "https://i.ibb.co/HXs7y1N/emperor-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"6",
//       "name": "The Lovers",
//       "description": "Choices, relationships, harmony.",
//       "image": "https://i.ibb.co/0nXsM3S/loversmajor.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"7",
//       "name": "The Chariot",
//       "description": "Determination, control, overcoming obstacles.",
//       "image": "https://i.ibb.co/m694R2K/chariot-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"8",
//       "name": "Strength",
//       "description": "Courage, inner strength, compassion.",
//       "image": "https://i.ibb.co/GT74ph8/strength-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"9",
//       "name": "The Hermit",
//       "description": "Solitude, introspection, inner guidance.",
//       "image": "https://i.ibb.co/DKzJpsD/hermit.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"10",
//       "name": "Wheel of Fortune",
//       "description": "Change, cycles, destiny.",
//       "image": "https://i.ibb.co/bFgjgJg/wheeloffortune.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"11",
//       "name": "Justice",
//       "description": "Fairness, balance, legal matters.",
//       "image": "https://i.ibb.co/v4ZX2n7/justice.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"12",
//       "name": "The Hanged Man",
//       "description": "Surrender, letting go, new perspective.",
//       "image": "https://i.ibb.co/bz86DjF/hangedmanaracana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"13",
//       "name": "Temperance",
//       "description": "Balance, harmony, moderation.",
//       "image": "https://i.ibb.co/X897BYj/temperance-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"14",
//       "name": "The Devil",
//       "description": "Temptation, bondage, materialism.",
//       "image": "https://i.ibb.co/rGGBtRs/devil-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"15",
//       "name": "The Tower",
//       "description": "Sudden change, upheaval, revelation.",
//       "image": "https://i.ibb.co/F7JMDrc/tower-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"16",
//       "name": "The Star",
//       "description": "Hope, inspiration, spirituality.",
//       "image": "https://i.ibb.co/L6Czshh/star-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"17",
//       "name": "The Moon",
//       "description": "Illusion, intuition, the subconscious.",
//       "image": "https://i.ibb.co/GpmPLBR/moon-aracana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"18",
//       "name": "The Sun",
//       "description": "Success, joy, vitality.",
//       "image": "https://i.ibb.co/wB2QY00/sun.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"19",
//       "name": "Judgement",
//       "description": "Reckoning, reflection, inner calling.",
//       "image": "https://i.ibb.co/1b8GSg3/judgementarcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     },
//     { "id":"20",
//       "name": "The World",
//       "description": "Completion, fulfillment, wholeness.",
//       "image": "https://i.ibb.co/TYzHw51/world-arcana.jpg",
//       "detail": " Ah, The Magician, a card that brings the magic of manifestation and potential. This card is usually numbered as I in the Tarot deck and holds a powerful symbolism.The Magician is often depicted standing before a table adorned with various tools and symbols representing the four elements: earth, air, fire, and water. In one hand, the Magician holds a wand, pointing it towards the sky, symbolizing the connection to the spiritual realm. The other hand points downwards, towards the earth, indicating the ability to manifest ideas and desires in the physical world.  This card signifies the power of transformation and the mastery of one's own destiny. The Magician is a bridge between the spiritual and material realms, suggesting that the querent has the tools and skills needed to bring their visions into reality. It's a card of creativity, willpower, and focused intention.  The Magician encourages taking initiative, tapping into one's potential, and being conscious of the energy and resources available. It often suggests a time of action and using one's talents and skills to achieve goals. This card reminds the querent that they have the power to shape their own reality.In a reversed position, The Magician may indicate a need to be cautious of one's intentions or a warning against manipulation. It could suggest a lack of focus or misuse of skills. However, it's essential to interpret reversals with nuance, as they can also signify a period of self-discovery and learning to harness one's power more responsibly.Overall, The Magician is a card of empowerment and the realization that the querent has the ability to create and transform their world through conscious intention and action."
//     }
//   ]
// }